//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ce.GEB_NGN_PCR_Practica1
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "GEB_NGN_PCR_prototools";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"GEB_NGN_PCR_Practica1";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"ce";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID GEB_NGN_PCR_Practica1DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GEB_NGN_PCR_Practica1CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID GEB_NGN_PCR_Practica1ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GEB_NGN_PCR_Practica1CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewGEB_NGN_PCR_Practica1ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(GEB_NGN_PCR_Practica1CommandSetId), 0x0001);
	
		// Package identifier
		public const string GEB_NGN_PCR_Practica1PackageId = "e0319584-b821-4bca-b15c-9b825d535441";
		
		// Editor factory identifier
		public const string GEB_NGN_PCR_Practica1EditorFactoryId = "36a3df3d-f3e7-47ec-9c76-2fa962f23a8e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string GEB_NGN_PCR_Practica1ModelExplorerToolWindowId = "0873e3eb-54f0-4101-8e85-c8a2d4ebd4cb";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace ce.GEB_NGN_PCR_Practica1
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string GEB_NGN_PCR_Practica1CommandSetId = "d86d3f2e-07c7-4bb2-8735-6bf9ada3fc90";
	}
}